### ISSUE TITLE
Add README with update instructions

### ISSUE THREAD

**Issue by dougmet** [MangoTheCat/rmdshower.mango#5]

**Comment by nathaneastwood** [comment]
I [added a basic README](a5e2193), not sure how much else you want to add? Maybe some badges? 
...
I'll add some badges

**Comment by nathaneastwood** [comment]
I fleshed it out [here](https://github.com/MangoTheCat/rmdshower.mango/commit/a80d8bd1e00717d34bde802c83469991374f4bc6) closing this issue now.
